### ISSUE TITLE
DsnParser - removing some special characters from shared key

### ISSUE THREAD

**Issue by norberttech** [AymDev/MessengerAzureBundle#15]
Hey!
I think this [urldecode](https://github.com/AymDev/MessengerAzureBundle/blob/main/src/Messenger/Transport/DsnParser.php#L168) is creating a small problem here. 

Azure Keys often will come with values like "+" inside of them which will end up replacing "+" with " " (empty space). 

https://3v4l.org/UoVYi#v8.3.2

**Comment by AymDev** [comment]
Hello, you can just encode the keys if you put them in the DSN, and ` +`  will become ` %2B` :
https://3v4l.org/7Rmll

**Comment by norberttech** [comment]
Yeah, I'm aware, I'm just not sure why it's done this way or why it's not at least mentioned in the documentation.
Might be worth mentioning in the docs, or removing that urldecode.

**Comment by AymDev** [comment]
Hello, sorry for the side effects. This won't be fixed in **v1.5** but I released [v2.0.0](https://github.com/AymDev/MessengerAzureBundle/releases/tag/v2.0.0) documenting the need for URL encoding the keys in the DSN.

As for why it's done this way: the DSN is exactly like a URL and parsing it as such makes it easier to do, and more reliable. Official Symfony Messenger transports also do the same.

If you don't want to encode your keys, you can stay with the **v1.4**.

**Comment by norberttech** [comment]
> As for why it's done this way: the DSN is exactly like a URL and parsing it as such makes it easier to do, and more reliable. Official Symfony Messenger transports also do the same.

Right, in that case it makes sense to keep it consistent and mentioning this in the documentation also sounds like a good solution. Thanks!
