### ISSUE TITLE
Base Endpoint has fixed scheme and domain

### ISSUE THREAD

**Issue by mark-newman** [AymDev/MessengerAzureBundle#5]
It would be great if this could support the use of azurite in a docker container. It doesn't feel like it's far away but the getBaseEndpoint has fixed portions which means you can't fully control the request URL with config so there's no way of hitting your local azurite instance.

**Comment by AymDev** [comment]
I don't know much about Azurite but from what I read, ASB and Azurite are two different tools. I guess that's why you closed this issue.

If you need multiple developers working on the same topic, you can create multiple subscriptions on the same topic. For queues I guess you'd need to create multiple namespaces.
